### ISSUE TITLE
求关闭项目的源码

### ISSUE THREAD

**Issue by hoixding** [babalae/bookmarklet#1]
在这个response下提issue是不得已为之。
我之前曾和你讨论过那个小工具的改进问题，现在它没了，值得吐槽的是，我没有保存源码。
我希望能从这里重新获得源码，以期由我来改进并重新发布。

**Comment by huiyadanli** [comment]
是那个自动钓鱼的小工具吗？

**Comment by hoixding** [comment]
对的

**Comment by huiyadanli** [comment]
那个项目，我会准备过一段时间改名重新在Github上放出的。

如果你有参与意愿可以直接发起PR

当前gitee的镜像repo还在的：
https://gitee.com/babalae/genshin-auto-fish

**Comment by hoixding** [comment]
感谢

**Comment by huiyadanli** [comment]
新地址 https://github.com/babalae/genshin-fishing-toy
